---
- name: Restart all services
  hosts: all
  become: true
  tasks:
    - name: Restart Web Server
      service:
        name: sshd  # Replace 'apache2' with 'sshd' for testing
        state: restarted

    - name: Restart API Services
      service:
        name: cron  # Replace 'api_service' with 'cron' for testing
        state: restarted
